apiVersion: batch/v1
kind: Job
metadata:
  name: trigger-postdeploy-pipeline
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  template:
    spec:
      containers:
        - name: test
          image:  registry.access.redhat.com/ubi8/ubi
          command:
            - /bin/bash
            - -c
            - 'echo TODO: trigger post deployment pipeline. Maybe make this a task instead?'
      restartPolicy: Never
  backoffLimit: 2
