apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo-tekton-argocd-dev
commonLabels:
  environment: dev

resources:
  - ../../../base

components:
  - ../../../components/route
  - ../../../components/hooks

patches:
  - path: patches/route.yml

configMapGenerator:
  - name: pet-battle-ui-config
    behavior: merge
    files:
      - files/config.json
