apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: pet-battle-ui
  app.kubernetes.io/component: pet-battle-ui
  app.kubernetes.io/instance: pet-battle-ui
  app.kubernetes.io/part-of: pet-battle
  app.kubernetes.io/version: latest

resources:
  - deployment.yml
  - service.yml

configMapGenerator:
  - name: pet-battle-ui-config
    files:
      - files/config.json
